
- name: ADD APPLICATION USER
  ansible.builtin.user:
    name: "{{application_user}}"

- name: REMOVE DEFAULT WEBSERVER CONTENT
  ansible.builtin.file:
    path: /app
    state: absent

- name: CREATE APPLICATION DIRECTORY
  ansible.builtin.file:
    path: /app
    state: directory

- name: DOWNLOAD THE APP CONTENT & UNZIP THE APP CONTENT
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component_name}}.zip
    dest: /app
    remote_src: yes

- name: DOWNLOAD THE APP CONTENT & UNZIP THE APP CONTENT
  ansible.builtin.unarchive:
    src: http://172.31.95.142:8081/repository/{{component_name}}/{{component_name}}-{{ lookup('aws_ssm', '{{ env }}.{{component_name}}.app_version', region='us-east-1' ) }}.zip
    dest: /app
    remote_src: yes