
- name : CONFIGURE NODE JS REPO
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: INSTALL NODE JS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: IMPORT/CALL APP_PREQUISITE YML
  ansible.builtin.import_tasks:
    file: app_requisite.yml

- name: INSTALL NODEJS DEPENDENCIES
  ansible.builtin.shell: npm install
  args :
    chdir : /app

- name: IMPORT/SCHEMA_SETUP
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: IMPORT/SYSTEMD_SETUP
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name : Import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter