- name : Load Mongod Schema
  when : schema_setup == "mongo"
  block:
    - name : COPY REPO FILE TO YUM.REPO.D
      ansible.builtin.copy:
        src : mongod.repo
        dest : /etc/yum.repos.d/mongod.repo

    - name : INSTALL MONGOD CLIENT
      ansible.builtin.yum:
        name:  mongodb-org-shell
        state: installed

    - name: Download DocDB PEM File
      ansible.builtin.get_url:
        url: https://truststore.pki.rds.amazonaws.com/us-east-1/us-east-1-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    - name : LOAD THE MONGODB SCEHMA
      ansible.builtin.shell : mongo --ssl --host {{ lookup('aws_ssm', '{{ env }}.docdb.db_endpoint', region='us-east-1' ) }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', '{{ env }}.docdb.db_user', region='us-east-1' ) }} --password {{ lookup('aws_ssm', '{{ env }}.docdb.db_pass', region='us-east-1' ) }} </app/schema/{{component_name}}.js



- name : Load mysql Schema
  when : schema_setup == "mysql"
  block:
    - name : INSTALL MYSQL CLIENT
      ansible.builtin.yum:
        name:  mysql
        state: installed

    - name : LOAD THE MYSQL SCEHMA
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', '{{ env }}.rds.db_host', region='us-east-1' ) }}  -u{{ lookup('aws_ssm', '{{ env }}.rds.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', '{{ env }}.rds.db_pass', region='us-east-1' ) }} < /app/schema/{{component_name}}.sql