groups:
- name: ec2 nodes
  rules:
  - alert: HighCPUutilization
    expr: 100-(avg by (component_name,env,instance,name) (rate(node_cpu_seconds_total{mode="idle"}[1m]) *100)) > 40
    for: 1m
    labels:
      severity: page
    annotations:
      summary: High CPU latency/usage


  - alert: HighMemoryutilization
      expr: 100-(100 * ((node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes)) > 40
      for: 1m
      labels:
        severity: page
      annotations:
        summary: High Memory latency/usage

  - alert: ServerDown
        expr: up < 1
        for: 1m
        labels:
          severity: page
        annotations:
          summary: Server Down


  - alert: ServiceDown
          expr: up < 1
          for: 1m
          labels:
            severity: page
          annotations:
            summary: Server Down

